<a href="https://colab.research.google.com/github/KshitijNachanekar/python/blob/main/2Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


## Slicing Syntax
array[start:end]

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[-3:])

[20 30 40]
[10 20 30]
[30 40 50]
[30 40 50]


# Numpy Functions

In [ ]:
# arrange()
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [ ]:
#Zeros()
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
#ones()
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
# sum(), mean(),max(),min()
marks = np.array([70,80,90,60])

print("sum:",np.sum(marks))
print("Average:",np.mean(marks))
print("Max:",np.max(marks))
print("min:",np.min(marks))

sum: 300
Average: 75.0
Max: 90
min: 60


# 2D Numpy Array

In [3]:
import numpy as np
arr=np.array([
    [10,20,30,14],
    [40,50,60,24],
    [70,80,90,34],
    [11,22,33,44]
])
print(arr)
print(arr.shape)
print(arr[0,2]) #indexing
print(arr[1:3,1:3]) #slicing
print(arr+2)
print(arr*2)

[[10 20 30 14]
 [40 50 60 24]
 [70 80 90 34]
 [11 22 33 44]]
(4, 4)
30
[[50 60]
 [80 90]]
[[12 22 32 16]
 [42 52 62 26]
 [72 82 92 36]
 [13 24 35 46]]
[[ 20  40  60  28]
 [ 80 100 120  48]
 [140 160 180  68]
 [ 22  44  66  88]]


In [ ]:
#axis=0 / column
#axis=1 / row

In [6]:
marks= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print("average marks",np.mean(marks,axis=1))
print("average marks",np.mean(marks,axis=0))

average marks [20. 50. 80.]
average marks [40. 50. 60.]
